"""Fixed Ozon Seller API origin and PR-API1 connection probe."""

OZON_API_BASE = "https://api-seller.ozon.ru"
CONNECTION_TEST_PATH = "/v1/seller/info"
FBO_POSTINGS_PATH = "/v3/posting/fbo/list"
FBS_POSTINGS_PATH = "/v4/posting/fbs/list"
CLUSTERS_V2_PATH = "/v2/cluster/list"
CLUSTERS_V1_PATH = "/v1/cluster/list"
SELLER_WAREHOUSES_PATH = "/v1/warehouse/fbo/seller/list"
FBO_STOCK_PATH = "/v1/analytics/stocks"
PRODUCT_LIST_PATH = "/v3/product/list"
FBS_STOCK_PATH = "/v2/product/info/stocks-by-warehouse/fbs"
SUPPLY_ORDER_LIST_PATH = "/v3/supply-order/list"
SUPPLY_ORDER_GET_PATH = "/v3/supply-order/get"
SUPPLY_ORDER_BUNDLE_PATH = "/v1/supply-order/bundle"
PLACEMENT_ZONE_PATH = "/v1/product/placement-zone/info"
HANDOFF_SEARCH_PATH = "/v1/warehouse/fbo/list"
DRAFT_CROSSDOCK_CREATE = "/v1/draft/crossdock/create"
DRAFT_DIRECT_CREATE = "/v1/draft/direct/create"
DRAFT_MULTI_CLUSTER_CREATE = "/v1/draft/multi-cluster/create"
DRAFT_CREATE_INFO = "/v2/draft/create/info"
DRAFT_TIMESLOT_INFO = "/v2/draft/timeslot/info"
